In [11]:
import numpy as np
import qutip as qt

In [12]:
ket_0 = qt.basis(2, 0)
ket_1 = qt.basis(2, 1)

ket_00 = qt.tensor(ket_0, ket_0)
ket_11 = qt.tensor(ket_1, ket_1)
ket_01 = qt.tensor(ket_0, ket_1)
ket_10 = qt.tensor(ket_1, ket_0)

a = (np.sqrt(5) - 1) / 2

ket_phi = a * (ket_01 + ket_10) + np.sqrt(1-2*a**2) * ket_11
ket_phi

Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.61803399]
 [0.61803399]
 [0.48586827]]

In [13]:
rho_phi = ket_phi * ket_phi.dag()
rho_phi

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.         0.         0.         0.        ]
 [0.         0.38196601 0.38196601 0.30028311]
 [0.         0.38196601 0.38196601 0.30028311]
 [0.         0.30028311 0.30028311 0.23606798]]

In [14]:
proj_0 = ket_0 * ket_0.dag()
proj_1 = ket_1 * ket_1.dag()

psi = 1 / np.sqrt(1-a**2) * (np.sqrt(1-2*a**2) * ket_0 - a * ket_1)
proj_psi = psi * psi.dag()

proj_0, proj_1, proj_psi, 1 - proj_psi

(Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
 Qobj data =
 [[1. 0.]
  [0. 0.]],
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
 Qobj data =
 [[0. 0.]
  [0. 1.]],
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
 Qobj data =
 [[ 0.38196601 -0.48586827]
  [-0.48586827  0.61803399]],
 Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
 Qobj data =
 [[0.61803399 0.48586827]
  [0.48586827 0.38196601]])

In [29]:
def p(a, b, x, y):
    if x == 1:
        proj_a = proj_0 if a == 0 else proj_1
    else:
        proj_a = proj_psi if a == 0 else (1 - proj_psi)

    if y == 1:
        proj_b = proj_0 if b == 0 else proj_1
    else:
        proj_b = proj_psi if b == 0 else (1 - proj_psi)

    proj_ab = qt.tensor(proj_a, proj_b)
    return (proj_ab * rho_phi).tr()

p(0, 1, 0, 1), p(1,0,1,0), p(0,0,1,1), p(0,0,0,0)

(0.0, 0.0, 0.0, (0.09016994374947418+0j))

Note - the above has the definition of x swapped, so that when x=0, we project in the psi basis, and when x=1, we project in the logical basis